import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
    pedantic: "off",
    style: "off",
    restriction: "off",
  },
  options: {
    reportUnusedDisableDirectives: "error",
  },
  ignorePatterns: [
    "node_modules/**",
    ".next/**",
    "dist/**",
    "coverage/**",
    "*.d.ts",
    "tools/oxlint/anti-slop/**",
    "tools/oxlint/alepes/**",
    "**/*.test.ts",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    { name: "alepes", specifier: "./tools/oxlint/alepes/index.ts" },
  ],
  rules: {
    "eslint/no-unused-vars": "warn",
    "unicorn/no-empty-file": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/require-post-message-target-origin": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-dupe-else-if": "warn",
    "eslint/no-await-in-loop": "warn",
    "eslint/no-useless-catch": "warn",
    "eslint/preserve-caught-error": "warn",
    "eslint/no-shadow": "warn",
    "anti-slop/no-chained-type-assertions": "warn",
    "anti-slop/no-conditional-empty-object-spread": "warn",
    "anti-slop/no-known-value-widening": "warn",
    "anti-slop/no-module-mocking": "warn",
    "anti-slop/no-object-parameters": "warn",
    "anti-slop/no-reflect-apply": "warn",
    "anti-slop/no-reflect-get": "warn",
    "anti-slop/no-runtime-typeof": ["warn", { allowInTypeGuards: true }],
    "anti-slop/no-shape-in-symbol-names": "off",
    "anti-slop/no-unknown-parameters": "off",
    "anti-slop/no-unknown-returns": "warn",
    "anti-slop/no-unknown-type-aliases": "warn",
    "anti-slop/no-unsafe-dictionary-type": "warn",
    "anti-slop/no-widen-then-assert": "warn",
    "anti-slop/require-safety-comment-for-type-assertion": "warn",
    "alepes/no-float-money": "warn",
    "alepes/no-provider-call-from-domain": "warn",
    "alepes/no-provider-id-in-financial-policy": "warn",
    "alepes/no-direct-broker-execution": "warn",
    "alepes/require-execution-policy": "warn",
    "alepes/no-nondeterminism-in-workflow": "warn",
    "alepes/no-duckdb-outside-analytics": "warn",
  },
  overrides: [
    {
      // Production packages: promote anti-slop rules to errors, keep Alepes domain rules strict
      files: [
        "packages/money/**",
        "packages/domain/**",
        "packages/rules-engine/**",
        "packages/allocation-engine/**",
        "packages/execution-policy/**",
        "packages/persistence/**",
        "packages/integration-runtime/**",
        "packages/integration-conformance/**",
        "packages/integrations/**",
        "packages/temporal-workflows/**",
        "packages/analytics/**",
        "src/lib/domain/**",
        "src/lib/data/**",
        "src/app/**",
      ],
      rules: {
        // Anti-slop quality rules (enforce, but with safety-comment discipline)
        "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-known-value-widening": "warn",
        "anti-slop/no-object-parameters": "warn",
        "anti-slop/no-runtime-typeof": ["warn", { allowInTypeGuards: true }],
        "anti-slop/no-unsafe-dictionary-type": "warn",
        "anti-slop/require-safety-comment-for-type-assertion": "warn",
        "anti-slop/no-widen-then-assert": "warn",
        "anti-slop/no-unknown-returns": "warn",
        "anti-slop/no-unknown-type-aliases": "warn",
        // Alepes domain rules: these are load-bearing (float money, foreign providers, policy gate)
        "alepes/no-float-money": "error",
        "alepes/no-provider-call-from-domain": "error",
        "alepes/no-provider-id-in-financial-policy": "error",
        "alepes/no-direct-broker-execution": "error",
        "alepes/require-execution-policy": "warn",
        "alepes/no-nondeterminism-in-workflow": "error",
        "alepes/no-duckdb-outside-analytics": "error",
      },
    },
    {
      // Money package internals: constructors intentionally narrow branded types.
      files: ["packages/money/src/index.ts"],
      rules: {
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "anti-slop/no-chained-type-assertions": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
      },
    },
    {
      // Test files: keep all rules at warn
      files: [
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.ts",
        "**/test-*/**",
        "**/__tests__/**",
      ],
      rules: {
        "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-known-value-widening": "warn",
        "anti-slop/no-object-parameters": "warn",
        "anti-slop/no-runtime-typeof": ["warn", { allowInTypeGuards: true }],
        "anti-slop/no-unsafe-dictionary-type": "warn",
        "anti-slop/require-safety-comment-for-type-assertion": "warn",
        "anti-slop/no-widen-then-assert": "warn",
        "anti-slop/no-unknown-returns": "warn",
        "anti-slop/no-unknown-type-aliases": "warn",
        "alepes/no-float-money": "warn",
        "alepes/no-provider-call-from-domain": "warn",
        "alepes/no-provider-id-in-financial-policy": "warn",
        "alepes/no-direct-broker-execution": "warn",
        "alepes/require-execution-policy": "warn",
        "alepes/no-nondeterminism-in-workflow": "warn",
        "alepes/no-duckdb-outside-analytics": "warn",
      },
    },
  ],
});
